---
__default__:
  time: "0-01:00"
  threads: 1
  mem: 2000
  queue: "debug"
  error: "logs/%x_%j_%N.err"
  output: "logs/%x_%j_%N.log"

create_demultiplexed_BAM_umi:
  time: "4-00:00"
  mem: 22000
  queue: "medium"

mergeTrimReads_demultiplexed_BAM_umi:
  time: "4-00:00"
  mem: 12000
  queue: "medium"

create_BAM:
  time: "4-00:00"
  mem: 12000
  queue: "medium"

create_BAM_umi:
  time: "4-00:00"
  mem: 12000
  queue: "medium"

raw_counts:
  time: "0-22:00"
  mem: 6000
  queue: "medium"

raw_counts_umi:
  time: "0-22:00"
  mem: 6000
  queue: "medium"

statistic_correlate_BC_counts:
  time: "0-22:00"
  mem: 80000
  queue: "medium"

statistic_frequent_umis:
  time: "0-04:00"
  queue: "medium"

dna_rna_merge:
  time: "4-00:00"
  mem: 20000
  queue: "medium"

dna_rna_merge_counts:
  time: "0-10:00"
  queue: "medium"

createAssignmentPickleFile:
  mem: 10000

statistic_calc_correlations:
  time: "2-00:00"
  mem: 120000
  queue: "medium"

statistic_overlapBCs:
  time: "0-05:00"
  mem: 10000
  queue: "medium"

assignBarcodes:
  time: "4-00:00"
  queue: "medium"
  mem: 10000

statistic_barcode_base_composition:
  time: "1-00:00"
  queue: "medium"
  mem: 15000
