---
global:
  assignments:
    split_number: 300
experiments:
  test_basic_countSAMPLINGdist3:
    bc_length: 15
    umi_length: 10
    data_folder: resources/Count_Basic/data
    experiment_file: resources/experiment.csv
    demultiplex: False
    assignments:
      standard:
        type: file
        value: resources/SRR10800986_filtered_coords_to_barcodes.tsv.gz
    design_file: reseources/design.fa
    configs:
      threshold1Withsampling:
        bc_threshold: 1
        minDNACounts: 1
        minRNACounts: 1
        sampling:
          DNA:
            prop: 30000000
          RNA:
            prop: 50000000
