---
$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file

properties:
  # start_global
  global:
    type: object
    default:
      threads: 1
      assignments:
        split_number: 1
    properties:
      assignments:
        type: object
        properties:
          split_number:
            type: integer
            default: 1
        additionalProperties: false
      threads:
        type: integer
        default: 1
    additionalProperties: false
  # start_assignments
  assignments:
    description: Assignments to run with configurations
    type: object
    additionalProperties:
      description: name of the assignment
      type: object
      patternProperties:
        ^((sequence_length)|(alignment_start))$:
          type: object
          properties:
            min:
              type: integer
            max:
              type: integer
          additionalProperties: false
          required:
            - min
            - max
      properties:
        R1:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
        R2:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
        R3:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
        reference:
          type: string
        configs:
          type: object
          additionalProperties:
            type: object
            properties:
              min_support: # 3 recommended
                type: integer
              fraction: # 0.7 recommended
                type: number
                minimum: 0
                maximum: 1
              unknown_other:
                type: boolean
                default: false
              ambiguous:
                type: boolean
                default: false
            required:
              - min_support
              - fraction
            additionalProperties: false
          minProperties: 1
      required:
        - R1
        - R2
        - R3
        - reference
        - configs
        - alignment_start
        - sequence_length
      additionalProperties: false
  # start_experiments
  experiments:
    description: MPRA experiments to run with configurations
    type: object
    additionalProperties:
      description: name of the experiment
      type: object
      properties:
        bc_length:
          type: integer
        umi_length:
          type: integer
        data_folder:
          type: string
        experiment_file:
          type: string
        demultiplex:
          type: boolean
        design_file:
          type: string
        label_file:
          type: string
        assignments:
          type: object
          additionalProperties:
            type: object
            properties:
              type:
                type: string
                enum:
                  - file
                  - config
              value:
                type: string
              sampling:
                type: object
                properties:
                  prop:
                    type: number
                  total:
                    type: integer
                additionalProperties: false
            required:
              - type
              - value
            additionalProperties: false
        configs:
          type: object
          additionalProperties:
            type: object
            properties:
              filter:
                type: object
                properties:
                  bc_threshold:
                    type: integer
                    default: 10
                patternProperties:
                  ^((DNA)|(RNA))$:
                    type: object
                    properties:
                      min_counts:
                        type: integer
                        default: 1
                    additionalProperties: false
                    required:
                      - min_counts
                required:
                  - bc_threshold
                  - DNA
                  - RNA
                additionalProperties: false
              sampling:
                type: object
                patternProperties:
                  ^((DNA)|(RNA))$:
                    type: object
                    properties:
                      threshold:
                        type: integer
                      prop:
                        type: number
                      total:
                        type: number
                      seed:
                        type: integer
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
            required:
              - filter
        variants:
          type: object
          properties:
            map:
              type: string
            min_barcodes:
              type: array
              items:
                type: integer
          required:
            - map
            - min_barcodes
      # entries that have to be in the config file for successful validation
      required:
        - bc_length
        - umi_length
        - data_folder
        - experiment_file
        - demultiplex
        - design_file
        - assignments
        - configs
# end_experiments
additionalProperties: false
minProperties: 1
